"""
Honeypot System - Advanced Flask Backend
Purpose: Technical demonstration of XSS detection and threat intelligence.
"""

import os
import json
import hashlib
import re
import glob
import socket
from datetime import datetime, timedelta
from urllib.parse import unquote, urlparse
import base64
from collections import defaultdict
import time
import joblib
import numpy as np

from flask import Flask, request, jsonify, render_template, redirect, url_for, session
from flask_cors import CORS
from flask_sqlalchemy import SQLAlchemy
from dotenv import load_dotenv
import requests

# Load environment variables
load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv('SECRET_KEY', 'default_secret_key_change_me')
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL', 'sqlite:///honeypot.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
CORS(app)

# --- Database Models ---

class AttackLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    attack_type = db.Column(db.String(50))
    payload = db.Column(db.Text)
    payload_hash = db.Column(db.String(64))
    ip_address = db.Column(db.String(50))
    user_agent = db.Column(db.Text)
    referer = db.Column(db.Text)
    method = db.Column(db.String(10))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    detection_results = db.Column(db.Text)  # JSON string
    intelligence = db.Column(db.Text)       # JSON string (GeoIP, Attribution)

class SearchLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    search_query = db.Column(db.Text)
    ip_address = db.Column(db.String(50))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    is_suspicious = db.Column(db.Boolean, default=False)
    
class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    email = db.Column(db.String(100))
    comment_text = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    is_attack = db.Column(db.Boolean, default=False)

# --- Detection Engines ---

class PayloadDeobfuscator:
    @staticmethod
    def deobfuscate(text):
        if not text: return ""
        
        # 1. URL Decoding
        try:
            text = unquote(text)
        except: pass
        
        # 2. Base64 attempts
        b64_matches = re.findall(r'[A-Za-z0-9+/]{8,}=*', text)
        for match in b64_matches:
            try:
                decoded = base64.b64decode(match).decode('utf-8', errors='ignore')
                if any(kw in decoded.lower() for kw in ['script', 'alert', 'onload', 'onerror', 'eval']):
                    text = text.replace(match, decoded)
            except: pass
            
        # 3. String.fromCharCode
        char_code_matches = re.findall(r'String\.fromCharCode\((.*?)\)', text, re.I)
        for match in char_code_matches:
            try:
                chars = [chr(int(c.strip())) for c in match.split(',')]
                decoded = "".join(chars)
                text = text.replace(f"String.fromCharCode({match})", decoded)
            except: pass
            
        return text

class XSSDetector:
    # ── Paths to ML model artifacts (generated by train_model.py) ─────────────
    ML_MODEL_PATH      = os.path.join('ml_model', 'xss_model.pkl')
    ML_VECTORIZER_PATH = os.path.join('ml_model', 'tfidf_vectorizer.pkl')
    # Confidence threshold: ML prediction probability above this → XSS
    ML_CONFIDENCE_THRESHOLD = 0.60

    def __init__(self, payloads_dir):
        self.payloads_dir = payloads_dir
        self.core_patterns = [
            r'<script[^>]*>', r'javascript:', r'on\w+\s*=', r'alert\(',
            r'prompt\(', r'confirm\(', r'<svg[^>]*onload', r'onerror\s*=',
            r'document\.cookie', r'eval\(', r'base64', r'data:text/html',
            r'<iframe[^>]*', r'<object[^>]*', r'vbscript:'
        ]
        self.signatures = []
        self.load_signatures()
        self.deobfuscator = PayloadDeobfuscator()
        self._load_ml_model()

    def _load_ml_model(self):
        """Load the trained scikit-learn ML model and TF-IDF vectorizer."""
        self.ml_model      = None
        self.ml_vectorizer = None
        try:
            if os.path.exists(self.ML_MODEL_PATH) and os.path.exists(self.ML_VECTORIZER_PATH):
                self.ml_model      = joblib.load(self.ML_MODEL_PATH)
                self.ml_vectorizer = joblib.load(self.ML_VECTORIZER_PATH)
                print("[ML] XSS detection model loaded successfully.")
            else:
                print("[ML] WARNING: Model artifacts not found. "
                      "Run 'python train_model.py' to generate them. "
                      "Falling back to regex-only detection.")
        except Exception as e:
            print(f"[ML] ERROR loading model: {e}. Falling back to regex-only detection.")

    def load_signatures(self):
        self.signatures = list(self.core_patterns)
        if os.path.exists(self.payloads_dir):
            payload_files = glob.glob(os.path.join(self.payloads_dir, "*.txt"))
            for file_path in payload_files:
                try:
                    with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                        for line in f:
                            line = line.strip()
                            if line and len(line) > 8:
                                self.signatures.append(re.escape(line))
                except: pass
        print(f"[Signatures] Loaded {len(self.signatures)} XSS signatures.")

    def _ml_predict(self, text: str) -> dict:
        """Run the ML model and return prediction label and confidence.

        Returns:
            dict with keys:
                ml_is_xss     (bool)   – True if ML predicts XSS
                ml_confidence (float)  – Probability score [0.0 – 1.0] for XSS class
                ml_available  (bool)   – False when model artifacts are not loaded
        """
        if self.ml_model is None or self.ml_vectorizer is None:
            return {'ml_is_xss': False, 'ml_confidence': 0.0, 'ml_available': False}
        try:
            vec   = self.ml_vectorizer.transform([text])
            proba = self.ml_model.predict_proba(vec)[0]   # [P(benign), P(xss)]
            xss_prob = float(proba[1])
            return {
                'ml_is_xss':     xss_prob >= self.ML_CONFIDENCE_THRESHOLD,
                'ml_confidence': round(xss_prob, 4),
                'ml_available':  True
            }
        except Exception as e:
            print(f"[ML] Prediction error: {e}")
            return {'ml_is_xss': False, 'ml_confidence': 0.0, 'ml_available': False}

    def detect(self, input_string):
        """Combined regex + ML XSS detection.

        Detection strategy:
          1. De-obfuscate the input (URL decode, Base64, fromCharCode).
          2. Run regex/signature matching (fast, rule-based).
          3. Run ML model prediction (probabilistic).
          4. Flag as suspicious if EITHER method fires.

        Returns a dict suitable for JSON serialization and dashboard display.
        """
        if not input_string:
            return {
                'is_suspicious':        False,
                'detected_patterns':    [],
                'payload_length':       0,
                'ml_confidence':        0.0,
                'ml_available':         self.ml_model is not None,
                'detection_method':     'none'
            }

        # ── Step 1: De-obfuscate ────────────────────────────────────────────────
        deobfuscated = self.deobfuscator.deobfuscate(input_string)

        # ── Step 2: Regex / Signature detection ────────────────────────────────
        detected_patterns = []
        for pattern in self.core_patterns:
            if re.search(pattern, deobfuscated, re.IGNORECASE):
                detected_patterns.append(pattern)

        if len(detected_patterns) < 5:
            for pattern in self.signatures:
                if pattern in self.core_patterns:
                    continue
                try:
                    if re.search(pattern, deobfuscated, re.IGNORECASE):
                        detected_patterns.append(
                            pattern[:50] + '...' if len(pattern) > 50 else pattern
                        )
                        if len(detected_patterns) >= 10:
                            break
                except:
                    continue

        regex_hit = len(detected_patterns) > 0

        # ── Step 3: ML prediction ───────────────────────────────────────────────
        # Run on both original and de-obfuscated text (use whichever is more confident)
        ml_orig  = self._ml_predict(input_string)
        ml_deob  = self._ml_predict(deobfuscated)
        ml_conf  = max(ml_orig['ml_confidence'], ml_deob['ml_confidence'])
        ml_hit   = ml_conf >= self.ML_CONFIDENCE_THRESHOLD

        # Annotate detected_patterns with ML score for transparency
        if ml_hit and ml_orig['ml_available']:
            detected_patterns.append(
                f"[ML Model] XSS probability: {ml_conf * 100:.1f}%"
            )

        # ── Step 4: Combine ─────────────────────────────────────────────────────
        is_suspicious = regex_hit or ml_hit

        if regex_hit and ml_hit:
            detection_method = 'regex+ml'
        elif regex_hit:
            detection_method = 'regex'
        elif ml_hit:
            detection_method = 'ml_only'
        else:
            detection_method = 'none'

        return {
            'is_suspicious':        is_suspicious,
            'detected_patterns':    detected_patterns,
            'original_length':      len(input_string),
            'deobfuscated_preview': deobfuscated[:100] if deobfuscated != input_string else None,
            'ml_confidence':        ml_conf,
            'ml_available':         ml_orig['ml_available'],
            'detection_method':     detection_method
        }

# --- Intelligence & Monitoring ---

class IntelligenceEngine:
    @staticmethod
    def get_geoip(ip):
        if ip in ['127.0.0.1', '::1']:
            return {'city': 'Localhost', 'country': 'Internal', 'isp': 'Private Network'}
        try:
            response = requests.get(f"http://ip-api.com/json/{ip}", timeout=3)
            if response.status_code == 200:
                data = response.json()
                if data['status'] == 'success':
                    return {'city': data.get('city'), 'country': data.get('country'), 'isp': data.get('isp')}
        except: pass
        return {}

    @staticmethod
    def identify_bot(user_agent):
        ua_lower = user_agent.lower()
        bots = {'burp': 'Burp Suite', 'zap': 'OWASP ZAP', 'sqlmap': 'sqlmap', 'nikto': 'Nikto', 'acunetix': 'Acunetix', 'python-requests': 'Python Scanner', 'curl': 'cURL Client', 'nmap': 'Nmap'}
        for key, name in bots.items():
            if key in ua_lower: return name
        return "Likely Manual"

    @staticmethod
    def reverse_dns(ip):
        try: return socket.gethostbyaddr(ip)[0]
        except: return "Unknown"

class BehavioralMonitor:
    def __init__(self):
        self.request_history = defaultdict(list)
        self.threshold = 30 # Requests per minute
        
    def check_behavior(self, ip):
        now = time.time()
        self.request_history[ip] = [t for t in self.request_history[ip] if now - t < 60]
        self.request_history[ip].append(now)
        
        if len(self.request_history[ip]) > self.threshold:
            return True, len(self.request_history[ip])
        return False, len(self.request_history[ip])

class WebhookManager:
    @staticmethod
    def send_alert(attack_log_entry, intelligence):
        webhook_url = os.getenv('DISCORD_WEBHOOK_URL') or os.getenv('SLACK_WEBHOOK_URL')
        if not webhook_url: return
        
        payload = {
            "content": f"🚨 **Honeypot Alert: {attack_log_entry.attack_type.upper()}**",
            "embeds": [{
                "title": "Attack Details",
                "color": 15158332 if attack_log_entry.attack_type != 'reflected_xss' else 3447003,
                "fields": [
                    {"name": "IP Address", "value": attack_log_entry.ip_address, "inline": True},
                    {"name": "Location", "value": f"{intelligence['geoip'].get('city', 'Unknown')}, {intelligence['geoip'].get('country', 'Unknown')}", "inline": True},
                    {"name": "Attribution", "value": intelligence['bot_identity'], "inline": True},
                    {"name": "Payload", "value": f"```{attack_log_entry.payload[:500]}```"}
                ],
                "footer": {"text": f"Event Hash: {attack_log_entry.payload_hash[:16]}"}
            }]
        }
        try: requests.post(webhook_url, json=payload, timeout=5)
        except: pass

# --- Globals ---

detector = XSSDetector('payloads')
intel = IntelligenceEngine()
behavior = BehavioralMonitor()
webhooks = WebhookManager()

# --- Helpers ---

def get_client_info():
    ip = request.headers.get('X-Forwarded-For', request.remote_addr)
    return {
        'ip_address': ip,
        'user_agent': request.headers.get('User-Agent', 'Unknown'),
        'referer': request.headers.get('Referer', 'Direct'),
        'method': request.method
    }

def log_attack(attack_type, payload, detection_results):
    client = get_client_info()
    geodata = intel.get_geoip(client['ip_address'])
    bot_identity = intel.identify_bot(client['user_agent'])
    rdns = intel.reverse_dns(client['ip_address'])
    
    # Check for behavioral anomalies
    is_aggressive, count = behavior.check_behavior(client['ip_address'])
    if is_aggressive: bot_identity = f"Aggressive Scanner ({count} req/min)"
    
    intelligence_data = {'geoip': geodata, 'bot_identity': bot_identity, 'reverse_dns': rdns}
    
    log = AttackLog(
        attack_type=attack_type, payload=payload, payload_hash=hashlib.sha256(payload.encode()).hexdigest(),
        ip_address=client['ip_address'], user_agent=client['user_agent'], referer=client['referer'],
        method=client['method'], detection_results=json.dumps(detection_results), intelligence=json.dumps(intelligence_data)
    )
    db.session.add(log)
    db.session.commit()
    
    # --- JSON File Logging ---
    try:
        log_entry = {
            'attack_type': attack_type,
            'payload': payload,
            'client_info': client,
            'intelligence': intelligence_data,
            'detection_results': detection_results,
            'timestamp': datetime.utcnow().isoformat()
        }
        filename = f"attack_{datetime.utcnow().strftime('%Y%m%d_%H%M%S_%f')}.json"
        log_path = os.path.join('honeypot_logs', filename)
        with open(log_path, 'w') as f:
            json.dump(log_entry, f, indent=4)
    except Exception as e:
        print(f"Error writing JSON log: {e}")

    webhooks.send_alert(log, intelligence_data)

# --- Routes ---

@app.route('/')
@app.route('/index.html')
def index_page():
    return render_template('index.html')

# -- Deception & Deceptive Routes --

@app.route('/admin/login', methods=['GET', 'POST'])
@app.route('/wp-admin', methods=['GET', 'POST'])
def admin_trap():
    if request.method == 'POST':
        user = request.form.get('username') or request.form.get('log')
        password = request.form.get('password') or request.form.get('pwd')
        log_attack('admin_brute_force', f"User: {user} | Pass: {password}", {'is_suspicious': True, 'detected_patterns': ['Fake Login Interaction']})
        return render_template('admin_login.html', error="Security token expired. Authentication failed.")
    return render_template('admin_login.html')

@app.route('/.env')
@app.route('/config.php.bak')
@app.route('/etc/passwd')
def sensitive_file_trap():
    path = request.path
    log_attack('sensitive_file_access', f"Path attempted: {path}", {'is_suspicious': True, 'detected_patterns': ['Honeytoken Triggered']})
    return "Error: Restricted access to configuration files. This attempt has been logged.", 403

# -- Admin Dashboard Security --

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        password = request.form.get('password')
        if password == os.getenv('ADMIN_PASSWORD'):
            session['logged_in'] = True
            return redirect(url_for('dashboard_page'))
        return render_template('login.html', error="Invalid password")
    return render_template('login.html')

@app.route('/logout')
def logout():
    session.pop('logged_in', None)
    return redirect(url_for('login'))

@app.route('/dashboard')
@app.route('/dashboard.html')
def dashboard_page():
    if not session.get('logged_in'): return redirect(url_for('login'))
    return render_template('dashboard.html')

# -- Core Functionality --

@app.route('/search', methods=['GET', 'POST'])
def search_endpoint():
    query = request.args.get('q', '') if request.method == 'GET' else \
            (request.form.get('q', '') or (request.get_json().get('q', '') if request.is_json else ''))
    
    # Honey-field check
    h_field = request.args.get('url_callback') or request.form.get('url_callback')
    if h_field:
        log_attack('bot_detection', f"Honey-field 'url_callback' filled with: {h_field}", {'is_suspicious': True, 'detected_patterns': ['Honey-field Triggered']})
        
    client = get_client_info()
    det_results = detector.detect(query)
    
    search = SearchLog(search_query=query, ip_address=client['ip_address'], is_suspicious=det_results['is_suspicious'])
    db.session.add(search)
    db.session.commit()
    
    if det_results['is_suspicious']:
        log_attack('reflected_xss', query, det_results)
        
    return render_template('index.html', query=query)

@app.route('/api/add-comment', methods=['POST'])
def add_comment():
    data = request.get_json() if request.is_json else request.form
    
    # Honey-field check
    if data.get('form_token'):
        log_attack('bot_detection', f"Honey-field 'form_token' filled with: {data.get('form_token')}", {'is_suspicious': True, 'detected_patterns': ['Honey-field Triggered']})

    name, email, comment_text = data.get('name', ''), data.get('email', ''), data.get('comment', '')
    det_name, det_email, det_comment = detector.detect(name), detector.detect(email), detector.detect(comment_text)
    
    is_attack = any([det_name['is_suspicious'], det_email['is_suspicious'], det_comment['is_suspicious']])
    comment_rec = Comment(name=name, email=email, comment_text=comment_text, is_attack=is_attack)
    db.session.add(comment_rec)
    db.session.commit()
    
    if is_attack:
        log_attack('stored_xss', f"Name: {name} | Email: {email} | Comment: {comment_text}", {'name': det_name, 'email': det_email, 'comment': det_comment})
        
    return jsonify({'success': True, 'message': 'Comment added'})

@app.route('/api/get-comments', methods=['GET'])
def get_comments():
    comments = Comment.query.order_by(Comment.timestamp.desc()).limit(50).all()
    return jsonify({'comments': [{'name': c.name, 'comment': c.comment_text, 'timestamp': c.timestamp.isoformat()} for c in comments]})

@app.route('/api/stats', methods=['GET'])
def get_stats():
    if not session.get('logged_in'): return jsonify({'error': 'Unauthorized'}), 401
    total_attacks = AttackLog.query.count()
    reflected = AttackLog.query.filter_by(attack_type='reflected_xss').count()
    stored = AttackLog.query.filter_by(attack_type='stored_xss').count()
    unique_ips = db.session.query(AttackLog.ip_address).distinct().count()
    return jsonify({'total_attacks': total_attacks, 'reflected_xss_attempts': reflected, 'stored_xss_attempts': stored, 'unique_ips': unique_ips, 'total_searches': SearchLog.query.count(), 'total_comments': Comment.query.count()})

@app.route('/api/get-attack-logs', methods=['GET'])
def get_attack_logs():
    if not session.get('logged_in'): return jsonify({'error': 'Unauthorized'}), 401
    logs = AttackLog.query.order_by(AttackLog.timestamp.desc()).limit(100).all()
    formatted_logs = []
    for log in logs:
        formatted_logs.append({
            'attack_type': log.attack_type, 'payload': log.payload, 'payload_hash': log.payload_hash,
            'client_info': {'ip_address': log.ip_address, 'user_agent': log.user_agent, 'method': log.method, 'timestamp': log.timestamp.isoformat()},
            'detection_results': json.loads(log.detection_results), 'intelligence': json.loads(log.intelligence)
        })
    return jsonify({'attacks': formatted_logs})

@app.route('/api/get-search-logs', methods=['GET'])
def get_search_logs():
    if not session.get('logged_in'): return jsonify({'error': 'Unauthorized'}), 401
    logs = SearchLog.query.order_by(SearchLog.timestamp.desc()).limit(100).all()
    return jsonify({'searches': [{'query': l.search_query, 'client_info': {'ip_address': l.ip_address, 'timestamp': l.timestamp.isoformat()}, 'detection_results': {'is_suspicious': l.is_suspicious}} for l in logs]})

@app.route('/api/clear-logs', methods=['POST'])
def clear_logs():
    if not session.get('logged_in'): return jsonify({'error': 'Unauthorized'}), 401
    try:
        db.session.query(AttackLog).delete()
        db.session.query(SearchLog).delete()
        db.session.query(Comment).delete()
        db.session.commit()
        return jsonify({'success': True, 'message': 'All logs and data cleared successfully'})
    except Exception as e:
        db.session.rollback()
        return jsonify({'success': False, 'message': str(e)}), 500

if __name__ == '__main__':
    with app.app_context(): db.create_all()
    app.run(debug=True, host='0.0.0.0', port=5000)
